// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImages() {
  return window['go']['main']['App']['GetImages']();
}

export function GetTags(arg1) {
  return window['go']['main']['App']['GetTags'](arg1);
}
