// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImages():Promise<Array<string>>;

export function GetTags(arg1:string):Promise<Array<string>>;
